name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
    name: Build Dynamic Library
    steps:
      - name: Init Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/opencv/opencv/archive/4.6.0.zip','opencv.zip')
          7z x -aoa -oC:\ opencv.zip
          rm opencv.zip
      - name: Build
        run: |
          $Env:PATH = "C:\mingw64\bin;C:\ninja;$Env:PATH"
          cd C:\opencv-4.6.0
          mkdir build
          cd build
          cmake .. -G Ninja -D CMAKE_INSTALL_PREFIX=C:/opencv -D INSTALL_C_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF
          ninja
          ninja install
      - name: Package Library
        run: |
          7z a Opencv_MinGW64_Dynamic.7z C:\opencv
      - uses: actions/upload-artifact@v3
        with:
          name: Opencv_MinGW64_Dynamic
          path: Opencv_MinGW64_Dynamic.7z

  buildStatic:
    runs-on: windows-2019
    name: Build Static Library
    steps:
      - name: Init Env
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/opencv/opencv/archive/4.6.0.zip','opencv.zip')
          7z x -aoa -oC:\ opencv.zip
          rm opencv.zip
      - name: Build
        run: |
          $Env:PATH = "C:\mingw64\bin;C:\ninja;$Env:PATH"
          cd C:\opencv-4.6.0
          mkdir build
          cd build
          cmake .. -G Ninja -D CMAKE_INSTALL_PREFIX=C:/opencv -D INSTALL_C_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_SHARED_LIBS=OFF
          ninja
          ninja install
      - name: Package Library
        run: |
          7z a Opencv_MinGW64_Static.7z C:\opencv
      - uses: actions/upload-artifact@v3
        with:
          name: Opencv_MinGW64_Static
          path: Opencv_MinGW64_Static.7z
